SoundManager.init(16);
SoundManager.setResourcePath(__dir__ + "assets/sounds/");

SoundManager.registerSound("GeneratorLoop.ogg", "Generators/GeneratorLoop.ogg", true);
SoundManager.registerSound("GeothermalLoop.ogg", "Generators/GeothermalLoop.ogg", true);
SoundManager.registerSound("WatermillLoop.ogg", "Generators/WatermillLoop.ogg", true);
SoundManager.registerSound("WindGenLoop.ogg", "Generators/WindGenLoop.ogg", true);
SoundManager.registerSound("MassFabLoop.ogg", "Generators/MassFabricator/MassFabLoop.ogg", true);
SoundManager.registerSound("MassFabScrapSolo.ogg", "Generators/MassFabricator/MassFabScrapSolo.ogg");
SoundManager.registerSound("GeigerHighEU.ogg", "Generators/NuclearReactor/GeigerHighEU.ogg", true);
SoundManager.registerSound("GeigerLowEU.ogg", "Generators/NuclearReactor/GeigerLowEU.ogg", true);
SoundManager.registerSound("GeigerMedEU.ogg", "Generators/NuclearReactor/GeigerMedEU.ogg", true);
SoundManager.registerSound("NuclearReactorLoop.ogg", "Generators/NuclearReactor/NuclearReactorLoop.ogg", true);

SoundManager.registerSound("CompressorOp.ogg", "Machines/CompressorOp.ogg", true);
SoundManager.registerSound("ElectrolyzerLoop.ogg", "Machines/ElectrolyzerLoop.ogg", true);
SoundManager.registerSound("ExtractorOp.ogg", "Machines/ExtractorOp.ogg", true);
SoundManager.registerSound("InterruptOne.ogg", "Machines/InterruptOne.ogg");
SoundManager.registerSound("IronFurnaceOp.ogg", "Machines/IronFurnaceOp.ogg", true);
SoundManager.registerSound("MaceratorOp.ogg", "Machines/MaceratorOp.ogg", true);
SoundManager.registerSound("MachineOverload.ogg", "Machines/MachineOverload.ogg");
SoundManager.registerSound("MagnetizerLoop.ogg", "Machines/MagnetizerLoop.ogg", true);
SoundManager.registerSound("MinerOp.ogg", "Machines/MinerOp.ogg", true);
SoundManager.registerSound("PumpOp.ogg", "Machines/PumpOp.ogg", true);
SoundManager.registerSound("RecyclerOp.ogg", "Machines/RecyclerOp.ogg", true);
SoundManager.registerSound("TerraformerGenericloop.ogg", "Machines/TerraformerGenericloop.ogg", true);
SoundManager.registerSound("ElectroFurnaceLoop.ogg", "Machines/Electro Furnace/ElectroFurnaceLoop.ogg", true);
SoundManager.registerSound("ElectroFurnaceStart.ogg", "Machines/Electro Furnace/ElectroFurnaceStart.ogg");
SoundManager.registerSound("ElectroFurnaceStop.ogg", "Machines/Electro Furnace/ElectroFurnaceStop.ogg");
SoundManager.registerSound("InductionLoop.ogg", "Machines/Induction Furnace/InductionLoop.ogg", true);
SoundManager.registerSound("InductionStart.ogg", "Machines/Induction Furnace/InductionStart.ogg");
SoundManager.registerSound("InductionStop.ogg", "Machines/Induction Furnace/InductionStop.ogg");
SoundManager.registerSound("TeleChargedLoop.ogg", "Machines/Teleporter/TeleChargedLoop.ogg", true);
SoundManager.registerSound("TeleUse.ogg", "Machines/Teleporter/TeleUse.ogg");

SoundManager.registerSound("BatteryUse.ogg", "Tools/BatteryUse.ogg");
SoundManager.registerSound("dynamiteomote.ogg", "Tools/dynamiteomote.ogg");
SoundManager.registerSound("eat.ogg", "Tools/eat.ogg");
SoundManager.registerSound("InsulationCutters.ogg", "Tools/InsulationCutters.ogg");
SoundManager.registerSound("JetpackLoop.ogg", "Tools/JetpackLoop.ogg", true);
SoundManager.registerSound("NukeExplosion.ogg", "Tools/NukeExplosion.ogg");
SoundManager.registerSound("ODScanner.ogg", "Tools/ODScanner.ogg");
SoundManager.registerSound("Painter.ogg", "Tools/Painter.ogg");
SoundManager.registerSound("RubberTrampoline.ogg", "Tools/RubberTrampoline.ogg");
SoundManager.registerSound("Treetap.ogg", "Tools/Treetap.ogg");
SoundManager.registerSound("Wrench.ogg", "Tools/Wrench.ogg");
SoundManager.registerSound("ChainsawIdle.ogg", "Tools/Chainsaw/ChainsawIdle.ogg", true);
SoundManager.registerSound("ChainsawStop.ogg", "Tools/Chainsaw/ChainsawStop.ogg");
SoundManager.registerSound("ChainsawUseOne.ogg", "Tools/Chainsaw/ChainsawUseOne.ogg");
SoundManager.registerSound("ChainsawUseTwo.ogg", "Tools/Chainsaw/ChainsawUseTwo.ogg");
SoundManager.registerSound("DrillHard.ogg", "Tools/Drill/DrillHard.ogg");
SoundManager.registerSound("DrillSoft.ogg", "Tools/Drill/DrillSoft.ogg");
SoundManager.registerSound("DrillUseLoop.ogg", "Tools/Drill/DrillUseLoop.ogg", true);
SoundManager.registerSound("MiningLaser.ogg", "Tools/MiningLaser/MiningLaser.ogg");
SoundManager.registerSound("MiningLaserExplosive.ogg", "Tools/MiningLaser/MiningLaserExplosive.ogg");
SoundManager.registerSound("MiningLaserLongRange.ogg", "Tools/MiningLaser/MiningLaserLongRange.ogg");
SoundManager.registerSound("MiningLaserLowFocus.ogg", "Tools/MiningLaser/MiningLaserLowFocus.ogg");
SoundManager.registerSound("MiningLaserScatter.ogg", "Tools/MiningLaser/MiningLaserScatter.ogg");
SoundManager.registerSound("NanosaberIdle.ogg", "Tools/Nanosaber/NanosaberIdle.ogg", true);
SoundManager.registerSound("NanosaberPowerup.ogg", "Tools/Nanosaber/NanosaberPowerup.ogg");
SoundManager.registerSound("NanosaberSwing.ogg", ["Tools/Nanosaber/NanosaberSwing1.ogg", "Tools/Nanosaber/NanosaberSwing2.ogg", "Tools/Nanosaber/NanosaberSwing3.ogg"]);
SoundManager.registerSound("QuantumsuitBoots.ogg", "Tools/QuantumSuit/QuantumsuitBoots.ogg");
