var ICAudioManager = new SoundManager(16);
ICAudioManager.setResourcePath(__dir__ + "res/sounds/");

ICAudioManager.registerSound("GeneratorLoop.ogg", "Generators/GeneratorLoop.ogg", true);
ICAudioManager.registerSound("GeothermalLoop.ogg", "Generators/GeothermalLoop.ogg", true);
ICAudioManager.registerSound("WatermillLoop.ogg", "Generators/WatermillLoop.ogg", true);
ICAudioManager.registerSound("WindGenLoop.ogg", "Generators/WindGenLoop.ogg", true);
ICAudioManager.registerSound("MassFabLoop.ogg", "Generators/MassFabricator/MassFabLoop.ogg", true);
ICAudioManager.registerSound("MassFabScrapSolo.ogg", "Generators/MassFabricator/MassFabScrapSolo.ogg");
ICAudioManager.registerSound("GeigerHighEU.ogg", "Generators/NuclearReactor/GeigerHighEU.ogg", true);
ICAudioManager.registerSound("GeigerLowEU.ogg", "Generators/NuclearReactor/GeigerLowEU.ogg", true);
ICAudioManager.registerSound("GeigerMedEU.ogg", "Generators/NuclearReactor/GeigerMedEU.ogg", true);
ICAudioManager.registerSound("NuclearReactorLoop.ogg", "Generators/NuclearReactor/NuclearReactorLoop.ogg", true);

ICAudioManager.registerSound("CompressorOp.ogg", "Machines/CompressorOp.ogg", true);
ICAudioManager.registerSound("ElectrolyzerLoop.ogg", "Machines/ElectrolyzerLoop.ogg", true);
ICAudioManager.registerSound("ExtractorOp.ogg", "Machines/ExtractorOp.ogg", true);
ICAudioManager.registerSound("InterruptOne.ogg", "Machines/InterruptOne.ogg");
ICAudioManager.registerSound("IronFurnaceOp.ogg", "Machines/IronFurnaceOp.ogg", true);
ICAudioManager.registerSound("MaceratorOp.ogg", "Machines/MaceratorOp.ogg", true);
ICAudioManager.registerSound("MachineOverload.ogg", "Machines/MachineOverload.ogg");
ICAudioManager.registerSound("MagnetizerLoop.ogg", "Machines/MagnetizerLoop.ogg", true);
ICAudioManager.registerSound("MinerOp.ogg", "Machines/MinerOp.ogg", true);
ICAudioManager.registerSound("PumpOp.ogg", "Machines/PumpOp.ogg", true);
ICAudioManager.registerSound("RecyclerOp.ogg", "Machines/RecyclerOp.ogg", true);
ICAudioManager.registerSound("TerraformerGenericloop.ogg", "Machines/TerraformerGenericloop.ogg", true);
ICAudioManager.registerSound("ElectroFurnaceLoop.ogg", "Machines/Electro Furnace/ElectroFurnaceLoop.ogg", true);
ICAudioManager.registerSound("ElectroFurnaceStart.ogg", "Machines/Electro Furnace/ElectroFurnaceStart.ogg");
ICAudioManager.registerSound("ElectroFurnaceStop.ogg", "Machines/Electro Furnace/ElectroFurnaceStop.ogg");
ICAudioManager.registerSound("InductionLoop.ogg", "Machines/Induction Furnace/InductionLoop.ogg", true);
ICAudioManager.registerSound("InductionStart.ogg", "Machines/Induction Furnace/InductionStart.ogg");
ICAudioManager.registerSound("InductionStop.ogg", "Machines/Induction Furnace/InductionStop.ogg");
ICAudioManager.registerSound("TeleChargedLoop.ogg", "Machines/Teleporter/TeleChargedLoop.ogg", true);
ICAudioManager.registerSound("TeleUse.ogg", "Machines/Teleporter/TeleUse.ogg");

ICAudioManager.registerSound("BatteryUse.ogg", "Tools/BatteryUse.ogg");
ICAudioManager.registerSound("dynamiteomote.ogg", "Tools/dynamiteomote.ogg");
ICAudioManager.registerSound("eat.ogg", "Tools/eat.ogg");
ICAudioManager.registerSound("InsulationCutters.ogg", "Tools/InsulationCutters.ogg");
ICAudioManager.registerSound("JetpackLoop.ogg", "Tools/JetpackLoop.ogg", true);
ICAudioManager.registerSound("NukeExplosion.ogg", "Tools/NukeExplosion.ogg");
ICAudioManager.registerSound("ODScanner.ogg", "Tools/ODScanner.ogg");
ICAudioManager.registerSound("Painter.ogg", "Tools/Painter.ogg");
ICAudioManager.registerSound("RubberTrampoline.ogg", "Tools/RubberTrampoline.ogg");
ICAudioManager.registerSound("Treetap.ogg", "Tools/Treetap.ogg");
ICAudioManager.registerSound("Wrench.ogg", "Tools/Wrench.ogg");
ICAudioManager.registerSound("ChainsawIdle.ogg", "Tools/Chainsaw/ChainsawIdle.ogg", true);
ICAudioManager.registerSound("ChainsawStop.ogg", "Tools/Chainsaw/ChainsawStop.ogg");
ICAudioManager.registerSound("ChainsawUseOne.ogg", "Tools/Chainsaw/ChainsawUseOne.ogg");
ICAudioManager.registerSound("ChainsawUseTwo.ogg", "Tools/Chainsaw/ChainsawUseTwo.ogg");
ICAudioManager.registerSound("DrillHard.ogg", "Tools/Drill/DrillHard.ogg");
ICAudioManager.registerSound("DrillSoft.ogg", "Tools/Drill/DrillSoft.ogg");
ICAudioManager.registerSound("DrillUseLoop.ogg", "Tools/Drill/DrillUseLoop.ogg", true);
ICAudioManager.registerSound("MiningLaser.ogg", "Tools/MiningLaser/MiningLaser.ogg");
ICAudioManager.registerSound("MiningLaserExplosive.ogg", "Tools/MiningLaser/MiningLaserExplosive.ogg");
ICAudioManager.registerSound("MiningLaserLongRange.ogg", "Tools/MiningLaser/MiningLaserLongRange.ogg");
ICAudioManager.registerSound("MiningLaserLowFocus.ogg", "Tools/MiningLaser/MiningLaserLowFocus.ogg");
ICAudioManager.registerSound("MiningLaserScatter.ogg", "Tools/MiningLaser/MiningLaserScatter.ogg");
ICAudioManager.registerSound("NanosaberIdle.ogg", "Tools/Nanosaber/NanosaberIdle.ogg", true);
ICAudioManager.registerSound("NanosaberPowerup.ogg", "Tools/Nanosaber/NanosaberPowerup.ogg");
ICAudioManager.registerSound("NanosaberSwing.ogg", ["Tools/Nanosaber/NanosaberSwing1.ogg", "Tools/Nanosaber/NanosaberSwing2.ogg", "Tools/Nanosaber/NanosaberSwing3.ogg"]);
ICAudioManager.registerSound("QuantumsuitBoots.ogg", "Tools/QuantumSuit/QuantumsuitBoots.ogg");
